eureka:
    client:
        serviceUrl:
            defaultZone: http://eureka.didispace.com/eureka/
server:
    port: 1111
spring:
    application:
        name: cloud-config-server
    cloud:
        config:
            label: master
            server:
                git:
                    uri: https://github.com/gdh7732/cloud-vue-parent.git
                    search-paths: repo
