spring:
  application:
    name: ocean-eureka
  profiles:
    active: master

eureka:
  client:
    register-with-eureka: true # 由于该应用为注册中心，所以设置为false，代表不向注册中心注册自己
    fetch-registry: true # 由于注册中心的职责就是维护服务实例，他并不需要去检索服务，所以也设置为false
  server:
    enableSelfPreservation: true # 开启自我保护

# 开启权限认证
security:
  basic:
    enabled: true
  user:
    name: root
    password: root


