eureka:
    client:
        serviceUrl:
            defaultZone: http://eureka.didispace.com/eureka/
server:
    port: 8011
spring:
    application:
        name: config-server
    cloud:
        config:
            label: master
            server:
                git:
                    uri: https://github.com/gdh7732/spring-cloud.git
                    search-paths: repo
